FROM zeroman/base

RUN apt-get install -y --no-install-recommends \
        xbase-clients fonts-wqy-microhei fonts-dejavu fonts-vlgothic xkb-data \
        libglu1-mesa libegl1-mesa libglapi-mesa libegl1-mesa libgles2-mesa \
        libgl1-mesa-dri  dbus

# for firefox
RUN apt-get install -y --no-install-recommends \
        libgtk-3-0 libdbus-glib-1-2




