FROM zeroman/base

RUN apt-get install -y --no-install-recommends \
        xbase-clients fonts-wqy-microhei fonts-dejavu fonts-vlgothic \
        libglu1-mesa libegl1-mesa libglapi-mesa libgles1-mesa libgles2-mesa \
        libgl1-mesa-dri libegl1-mesa-drivers 



