FROM zeroman/x11

RUN apt-get install -y --no-install-recommends \
        openjdk-8-jdk proguard \
        maven ant gradle 

#RUN update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

