FROM zeroman/base

RUN apt-get install -y --no-install-recommends -t jessie-backports \
        openjdk-7-jdk openjdk-8-jdk proguard \
        maven maven2 ant gradle 

#RUN update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

