version: '3'

services:
  proxy:
    restart: always
    image: nginx:alpine
    volumes:
    - ./proxy.conf:/etc/nginx/conf.d/default.conf
    - ./proxy.crt:/etc/nginx/certs/proxy.crt
    - ./proxy.key:/etc/nginx/certs/proxy.key
    - ./www:/www
    ports:
    - "80:80"
    - "443:443"
