FROM zeroman/x11

RUN apt-get install -y --no-install-recommends qt5-default libqt5webchannel5 libqt5x11extras5

#RUN apt-get install -y --no-install-recommends lxterminal qt5-default qtcreator libqt5x11extras5

#ENV QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb

CMD ["bash"]
