FROM zm.base

RUN apt-get install -y --no-install-recommends \
        texlive-base texlive-fonts-recommended texlive-generic-recommended \
        texlive-pictures texlive-xetex \
        texlive-fonts-extra texlive-generic-extra texlive-lang-chinese \
        texlive-latex-base texlive-latex-recommended texlive-latex-extra \
        latex-cjk-chinese cjk-latex latex2html latex2rtf \
        latex-cjk-chinese-arphic-bkai00mp \
        latex-cjk-chinese-arphic-bsmi00lp \
        latex-cjk-chinese-arphic-gbsn00lp \
        latex-cjk-chinese-arphic-gkai00mp \
        latex-fonts-sipa-arundina \
        fonts-wqy-zenhei fonts-wqy-microhei \
        lmodern fonts-lmodern

CMD ["/bin/bash"]
